### ISSUE TITLE
Module path should be "github.com/lensesio/lenses-go", not "github.com/landoop/lenses-go"

### ISSUE THREAD

**Issue by KateGo520** [lensesio/lenses-go#80]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, run `go get github.com/lensesio/lenses-go@7ebcec6`:

```
go: downloading github.com/lensesio/lenses-go v0.0.0-20200410145700-7ebcec68b64a
go: github.com/lensesio/lenses-go 7ebcec6 => v0.0.0-20200410145700-7ebcec68b64a
go get: github.com/lensesio/lenses-go@v0.0.0-20200410145700-7ebcec68b64a: parsing go.mod:
        module declares its path as: github.com/landoop/lenses-go
                but was required as: github.com/lensesio/lenses-go 
```

###  Fix the module path:
1) Rename the module path to "github.com/lensesio/lenses-go": https://github.com/lensesio/lenses-go/blob/master/go.mod#L1:
```
module github.com/lensesio/lenses-go
go 1.13
require (
	…
) 
```
2) Warning the users not to use the module, get "github.com/lensesio/lenses-go" in GOPATH mode.

**Comment by KateGo520** [comment]
@deanlinaras  @stelispanagiotakis  Could you help me review this issue? Thx :p

**Comment by deanlinaras** [comment]
I reckon we have to fix all imports too :thinking:

**Comment by deanlinaras** [comment]
@KateGo520 have a look at https://github.com/lensesio/lenses-go/commit/b61b3b9047b61730b33ab8f5524aac4cb4c61386. I think it addresses all the issues that you raised.

**Comment by deanlinaras** [comment]
Closing this ticket as this has been addressed with commit shared above. Thank you

**Comment by KateGo520** [comment]
@deanlinaras    Thank you for your reply. I see the commit. Thant helps a lot! Thank you for your contribution!
