### ISSUE TITLE
`lenses-cli connectors` and `lenses-cli export connectors` return the same error

### ISSUE THREAD

**Issue by zacharykitt** [lensesio/lenses-go#83]
The lenses-cli (v5.0.1) returns the following error when attempting to export connectors:

```
[ERRO] 2022/06/16 22:02 Error writing connectors. [[lenses.kafka.connect.clusters]: couldn't find the corresponding key from config]
[lenses.kafka.connect.clusters]: couldn't find the corresponding key from config
```

The same error regarding a missing key can also be seen when running `lenses-cli connectors`. I see the missing `lenses.kafka.connect.clusters` key referenced in the [v4.3 docs](https://docs.lenses.io/4.3/configuration/connect/), but I am using Lenses v5.0.1 with the provision-cli creating the connection to Kafka Connect.

Note that I can get information about specific connectors if I run `lenses-cli connector --cluster-name="cluster-name" --name="connector-name"`.

**Comment by deanlinaras** [comment]
Hi Zacharykitt, closing this ticket down as we are handling them in zendesk.
